version: "3"
services:
    music-api-kr:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 5000:5000
        volumes:
            - /app/node_modules
            - .:/app
